import Link from 'next/link';

export const metadata = {
  title: 'Retail Intelligence OS — conversation intelligence for jewellery retail',
  description:
    'Every in-store conversation, turned into evidence a store manager can act on. Scores computed from quoted evidence, not generated by a model.',
};

/**
 * LANDING PAGE.
 *
 * Static. No database, no auth, no data fetching — it renders before the
 * engine has ever run, which matters because it is the first thing a judge or
 * a GIVA stakeholder sees.
 *
 * The argument it makes, in order: most conversation-analytics tools hand you
 * a number you cannot audit; we hand you the sentence the number came from;
 * and we are the only ones connecting what was said to whether it sold.
 */

const NAV = [
  { href: '#problem', label: 'Problem' },
  { href: '#how', label: 'How it works' },
  { href: '#evidence', label: 'Evidence' },
  { href: '#agents', label: 'Agents' },
];

const AGENTS = [
  { n: 'A1', name: 'Hospitality', desc: 'Greeting, water, seating, companions, patience, farewell — seven checks, each with a quote.' },
  { n: 'A2', name: 'Sales effectiveness', desc: 'Discovery, storytelling, objection handling, upsell, close, contact capture. Judged on the attempt, not the outcome.' },
  { n: 'A3', name: 'Accuracy & compliance', desc: 'Wrong claims, missing disclosures, making charges, and whether the live offer was actually mentioned.' },
  { n: 'A4', name: 'Customer signal', desc: 'Intent, occasion, budget, urgency and the one thing that blocked the sale.' },
  { n: 'A5', name: 'Summary & coaching', desc: 'What happened, and the exact Hinglish line the associate could have used instead.' },
  { n: 'A6', name: 'Demand intelligence', desc: 'What customers asked for, what you could not supply, and which collections came up.' },
  { n: 'A7', name: 'Aggregation', desc: 'The only agent with a global view. Writes the manager narrative and ranks the actions.' },
];

const STEPS = [
  { n: '01', t: 'Capture', d: 'Record on any device, or ingest a transcript directly. The engine consumes transcripts, not audio — so it runs before you own a single microphone.' },
  { n: '02', t: 'Transcribe & redact', d: 'Speaker-diarized Hinglish transcription. Names, numbers and card digits are stripped before anything is stored.' },
  { n: '03', t: 'Identify who spoke', d: 'Staff, customer, companion — with a confidence score that gates everything downstream. Below threshold, the visit is flagged rather than guessed at.' },
  { n: '04', t: 'Extract evidence', d: 'Six specialist agents run in parallel. Each reports observations with a verbatim quote. None of them produce a score.' },
  { n: '05', t: 'Compute the score', d: 'Deterministic code turns evidence into numbers using published weights. Same conversation, same score, every time.' },
  { n: '06', t: 'Act', d: 'Manager narrative, ranked actions, a coaching line per associate, and tomorrow\'s follow-up list.' },
];

export default function Landing() {
  return (
    <div className="min-h-screen bg-white text-ink">
      {/* ── Compliance strip ─────────────────────────────────────────── */}
      <div className="bg-ink text-stone-300 text-[11.5px] py-2 px-6 text-center">
        Transcripts are PII-redacted before storage · Consent captured per visit · Built for India&apos;s DPDP Act 2023
      </div>

      {/* ── Header ───────────────────────────────────────────────────── */}
      <header className="sticky top-0 z-20 bg-white/90 backdrop-blur border-b border-line">
        <div className="max-w-6xl mx-auto px-6 h-16 flex items-center justify-between">
          <Link href="/" className="flex items-center gap-2.5">
            <span className="w-8 h-8 rounded-lg grid place-items-center text-[13px] font-extrabold text-white"
              style={{ background: 'linear-gradient(135deg,#D99A2B,#B4780C)' }}>R</span>
            <span className="font-bold tracking-tight">Retail Intelligence OS</span>
          </Link>
          <nav className="hidden md:flex items-center gap-7 text-[13px] text-muted">
            {NAV.map((n) => <a key={n.href} href={n.href} className="hover:text-ink">{n.label}</a>)}
          </nav>
          <Link href="/dashboard" className="bg-ink text-white text-[13px] font-medium px-4 py-2 rounded-lg hover:bg-stone-700">
            Open dashboard
          </Link>
        </div>
      </header>

      {/* ── Hero ─────────────────────────────────────────────────────── */}
      <section className="max-w-6xl mx-auto px-6 pt-20 pb-16">
        <div className="max-w-3xl">
          <div className="inline-flex items-center gap-2 text-[11.5px] font-semibold text-accent bg-accent-soft border border-accent-line rounded-full px-3 py-1 mb-6">
            <span>◆</span> Built for Indian jewellery retail · Hinglish-first
          </div>
          <h1 className="text-[44px] sm:text-[56px] leading-[1.05] font-bold tracking-[-0.03em]">
            Every score traces back<br />to something a person said.
          </h1>
          <p className="mt-6 text-[17px] leading-relaxed text-stone-600 max-w-2xl">
            Your stores run thousands of customer conversations a week, and every one of them disappears the
            moment the customer leaves. Retail Intelligence OS turns them into evidence — what was offered, what
            was missed, what the customer actually wanted, and which of it made the sale.
          </p>
          <div className="mt-9 flex flex-wrap gap-3">
            <Link href="/dashboard" className="bg-ink text-white text-[14px] font-medium px-6 py-3 rounded-lg hover:bg-stone-700">
              Open the live dashboard
            </Link>
            <Link href="/visits" className="border border-line text-[14px] font-medium px-6 py-3 rounded-lg hover:border-ink">
              See a real analysed visit
            </Link>
          </div>
          <p className="mt-4 text-[12.5px] text-muted">
            Running on synthetic conversations — real recordings drop into the same pipeline unchanged.
          </p>
        </div>
      </section>

      {/* ── The differentiator ───────────────────────────────────────── */}
      <section id="evidence" className="border-y border-line bg-stone-50/60">
        <div className="max-w-6xl mx-auto px-6 py-16">
          <h2 className="text-[13px] uppercase tracking-[0.12em] text-muted font-semibold">The difference that matters</h2>
          <p className="mt-3 text-[28px] font-bold tracking-tight max-w-3xl leading-tight">
            Most conversation tools give you a number.<br />We give you the sentence it came from.
          </p>

          <div className="grid md:grid-cols-2 gap-5 mt-10">
            <div className="bg-white border border-line rounded-xl p-6">
              <div className="text-[11px] uppercase tracking-wider text-muted font-semibold mb-3">Typical approach</div>
              <div className="text-[40px] font-bold tabular-nums text-stone-400">87<span className="text-[18px] font-normal">/100</span></div>
              <div className="text-[13px] text-muted mt-1">Associate tone score</div>
              <ul className="mt-5 space-y-2 text-[13px] text-stone-600">
                <li className="flex gap-2"><span className="text-bad">✕</span> A model produced this number directly</li>
                <li className="flex gap-2"><span className="text-bad">✕</span> Re-run the same audio and it moves</li>
                <li className="flex gap-2"><span className="text-bad">✕</span> Nobody can explain it to the person being scored</li>
                <li className="flex gap-2"><span className="text-bad">✕</span> You cannot act on &ldquo;sentiment is 68% positive&rdquo;</li>
              </ul>
            </div>

            <div className="bg-white border-2 border-ink rounded-xl p-6">
              <div className="text-[11px] uppercase tracking-wider text-accent font-semibold mb-3">Retail Intelligence OS</div>
              <div className="space-y-2.5">
                <div className="flex gap-2.5 items-start text-[13px]">
                  <span className="text-good mt-0.5">✓</span>
                  <div><b>Greeted within 30s</b>
                    <div className="text-muted italic">&ldquo;Welcome to GIVA ma&apos;am, aaiye please&rdquo; · 0:02 · conf 0.99</div></div>
                </div>
                <div className="flex gap-2.5 items-start text-[13px]">
                  <span className="text-bad mt-0.5">✕</span>
                  <div><b>Making charges disclosed</b>
                    <div className="text-muted italic">&ldquo;Wo bill ke time bata denge aunty&rdquo; · 1:41 · conf 0.98</div></div>
                </div>
                <div className="flex gap-2.5 items-start text-[13px]">
                  <span className="text-warn mt-0.5">◐</span>
                  <div><b>Buyback policy stated</b>
                    <div className="text-muted">Audio unintelligible 12:10–12:35 — excluded from the score</div></div>
                </div>
              </div>
              <div className="mt-5 pt-4 border-t border-line text-[13px] text-stone-600">
                Agents extract evidence. <b>Code computes the score.</b> The same conversation produces the same
                number every time, every point is explainable line by line, and an uncertain observation is
                excluded rather than counted as a failure — nobody is penalised for a bad microphone.
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ── Problem ──────────────────────────────────────────────────── */}
      <section id="problem" className="max-w-6xl mx-auto px-6 py-20">
        <h2 className="text-[13px] uppercase tracking-[0.12em] text-muted font-semibold">The problem</h2>
        <p className="mt-3 text-[28px] font-bold tracking-tight max-w-3xl leading-tight">
          You know what sold. You have no idea what was said.
        </p>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-10">
          {[
            ['Why did that customer leave?', 'She spent forty minutes, approved a piece, and walked. Nobody can tell you what happened in the last two minutes.'],
            ['Is the offer being communicated?', 'You launched a festival offer across every store. You have no way to know whether anyone mentioned it.'],
            ['Who should we call tomorrow?', 'High-intent visitors leave every day without a follow-up, because nobody wrote down that they were high intent.'],
            ['Which associates actually sell well?', 'You can rank them by revenue. You cannot tell which behaviours produced it, so you cannot teach it.'],
            ['What are customers asking for?', 'Requests for things you do not stock never reach merchandising. They evaporate on the shop floor.'],
            ['Why is Store A beating Store B?', 'Same catalogue, same offers, twelve points of conversion apart. The reason is in the conversations.'],
          ].map(([q, a]) => (
            <div key={q} className="border border-line rounded-xl p-5">
              <div className="font-semibold text-[14px]">{q}</div>
              <div className="text-[13px] text-muted mt-2 leading-relaxed">{a}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── How it works ─────────────────────────────────────────────── */}
      <section id="how" className="border-y border-line bg-stone-50/60">
        <div className="max-w-6xl mx-auto px-6 py-20">
          <h2 className="text-[13px] uppercase tracking-[0.12em] text-muted font-semibold">How it works</h2>
          <p className="mt-3 text-[28px] font-bold tracking-tight">Six steps, ninety seconds per visit.</p>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-5 mt-10">
            {STEPS.map((s) => (
              <div key={s.n} className="bg-white border border-line rounded-xl p-5">
                <div className="text-[11px] font-bold text-accent tabular-nums">{s.n}</div>
                <div className="font-semibold text-[15px] mt-1.5">{s.t}</div>
                <div className="text-[13px] text-muted mt-2 leading-relaxed">{s.d}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ── Agents ───────────────────────────────────────────────────── */}
      <section id="agents" className="max-w-6xl mx-auto px-6 py-20">
        <h2 className="text-[13px] uppercase tracking-[0.12em] text-muted font-semibold">The agent network</h2>
        <p className="mt-3 text-[28px] font-bold tracking-tight max-w-3xl leading-tight">
          Seven specialists with narrow briefs, not one model asked to do everything.
        </p>
        <p className="mt-4 text-[15px] text-stone-600 max-w-2xl leading-relaxed">
          Each agent is a markdown prompt file with one job, a strict output schema, and a rule that it must quote
          the transcript for every claim. None of them can see each other&apos;s work — except the last one, whose
          whole purpose is to find the connection none of the others could see alone.
        </p>
        <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4 mt-10">
          {AGENTS.map((a) => (
            <div key={a.n} className="border border-line rounded-xl p-5 hover:border-ink transition-colors">
              <div className="flex items-center gap-2">
                <span className="text-[10.5px] font-bold text-white bg-ink rounded px-1.5 py-0.5 tabular-nums">{a.n}</span>
                <span className="font-semibold text-[14px]">{a.name}</span>
              </div>
              <div className="text-[13px] text-muted mt-2.5 leading-relaxed">{a.desc}</div>
            </div>
          ))}
        </div>
      </section>

      {/* ── Outcome linkage ──────────────────────────────────────────── */}
      <section className="border-y border-line bg-ink text-stone-200">
        <div className="max-w-6xl mx-auto px-6 py-20">
          <h2 className="text-[13px] uppercase tracking-[0.12em] text-stone-500 font-semibold">The part nobody else does</h2>
          <p className="mt-3 text-[28px] font-bold tracking-tight text-white max-w-3xl leading-tight">
            We join what was said to whether it sold.
          </p>
          <p className="mt-5 text-[15px] leading-relaxed max-w-2xl text-stone-300">
            Conversation analytics that stops at &ldquo;sentiment was positive&rdquo; cannot tell you whether any of it
            mattered. By joining every visit to its outcome, the system shows which behaviours actually move
            conversion — and which ones you have been coaching for no reason.
          </p>
          <div className="grid sm:grid-cols-3 gap-4 mt-10">
            {[
              ['Close attempted', 'the strongest lever we measure'],
              ['Budget asked early', 'shapes everything shown after it'],
              ['Live offer communicated', 'answers the objection that ends most visits'],
            ].map(([b, d]) => (
              <div key={b} className="border border-stone-700 rounded-xl p-5">
                <div className="font-semibold text-white text-[15px]">{b}</div>
                <div className="text-[13px] text-stone-400 mt-1.5">{d}</div>
              </div>
            ))}
          </div>
          <p className="mt-8 text-[12.5px] text-stone-500 max-w-2xl leading-relaxed">
            Current figures come from synthetic conversations and are labelled as such throughout the product. We
            publish our agreement rate against human labels, including where it is weak, because a number you
            cannot check is worth nothing.
          </p>
        </div>
      </section>

      {/* ── CTA ──────────────────────────────────────────────────────── */}
      <section className="border-t border-line bg-stone-50/60">
        <div className="max-w-6xl mx-auto px-6 py-16 text-center">
          <p className="text-[26px] font-bold tracking-tight">See it on a real conversation.</p>
          <p className="mt-3 text-[15px] text-stone-600 max-w-xl mx-auto">
            The dashboard is live with analysed visits — transcript, evidence, scores and coaching, end to end.
          </p>
          <div className="mt-7 flex flex-wrap gap-3 justify-center">
            <Link href="/dashboard" className="bg-ink text-white text-[14px] font-medium px-6 py-3 rounded-lg hover:bg-stone-700">
              Open dashboard
            </Link>
            <Link href="/ingest" className="border border-line bg-white text-[14px] font-medium px-6 py-3 rounded-lg hover:border-ink">
              Analyse a conversation
            </Link>
          </div>
        </div>
      </section>

      <footer className="max-w-6xl mx-auto px-6 py-10 text-[12.5px] text-muted flex flex-wrap gap-4 justify-between">
        <span>Retail Intelligence OS · Big Ears engine + RIO dashboards</span>
        <span>Built for GIVA · Hinglish-first · DPDP 2023 by design</span>
      </footer>
    </div>
  );
}
