import LandingPage from '@/components/landing-page';

export const metadata = {
  title: 'Retail Intelligence OS — conversation intelligence for retail',
  description:
    'Every in-store conversation, turned into evidence a store manager can act on. Scores computed from quoted evidence, not generated by a model.',
};

export default function Home() {
  return <LandingPage />;
}
