'use client';
import Link from 'next/link';
import { usePathname } from 'next/navigation';

const GROUPS = [
  { label: 'Analyse', items: [
    { href: '/dashboard', icon: '◉', label: 'Home' },
    { href: '/sales', icon: '◑', label: 'Sales' },
    { href: '/visits', icon: '◎', label: 'Conversations' },
    { href: '/customers', icon: '◍', label: 'Customers' },
    { href: '/demand', icon: '◇', label: 'Demand' },
  ]},
  { label: 'Act', items: [
    { href: '/coaching', icon: '◈', label: 'Coaching' },
    { href: '/followups', icon: '⟳', label: 'Follow-ups' },
    { href: '/copilot', icon: '✦', label: 'RIO Copilot' },
  ]},
  { label: 'Capture', items: [
    { href: '/ingest', icon: '⏺', label: 'Ingest recording' },
  ]},
  { label: 'Trust', items: [
    { href: '/review', icon: '⚑', label: 'Needs Review' },
  ]},
];

export default function Nav() {
  const path = usePathname();
  return (
    <aside className="w-[232px] flex-none bg-ink text-stone-200 px-3.5 py-5 flex flex-col gap-1 sticky top-0 h-screen overflow-y-auto">
      <Link href="/" className="flex items-center gap-2.5 px-2 pb-4">
        <span className="h-[26px] px-1.5 rounded-[7px] grid place-items-center text-[11px] font-extrabold tracking-tight text-white"
          style={{ background: 'linear-gradient(135deg,#D99A2B,#B4780C)' }}>RIO</span>
        <span>
          <b className="text-sm tracking-tight block">Retail Intelligence OS</b>
          <small className="text-stone-400 text-[11px]">Big Ears</small>
        </span>
      </Link>

      {GROUPS.map((g) => (
        <div key={g.label}>
          <div className="text-[10px] uppercase tracking-[0.09em] text-stone-500 px-2 pt-3.5 pb-1.5">{g.label}</div>
          {g.items.map((it) => {
            const on = path === it.href || (it.href !== '/' && path.startsWith(it.href));
            return (
              <Link key={it.href} href={it.href}
                className={`flex items-center gap-2.5 px-2.5 py-2 rounded-[7px] text-[13px] ${on ? 'bg-stone-600 text-white font-semibold' : 'text-stone-300 hover:bg-stone-800 hover:text-stone-50'}`}>
                <span className="w-4 text-center opacity-85 text-[13px]">{it.icon}</span>{it.label}
              </Link>
            );
          })}
        </div>
      ))}

      <div className="mt-auto pt-3 px-2 border-t border-stone-800 text-[11px] text-stone-500 leading-relaxed">
        Scores are computed from<br />agent-extracted evidence,<br />not generated by a model.
      </div>
    </aside>
  );
}
