/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/stores": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All store locations. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Store"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Staff, optionally filtered to one store. */
        get: {
            parameters: {
                query?: {
                    store?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Staff"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/performance": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-associate scores and conversion across all scored visits. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["StaffPerformance"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Visit summaries, newest first.
         * @description Pass `range` for a relative window, or explicit `from`/`to`. `needsReview=true` powers the review queue.
         */
        get: {
            parameters: {
                query?: {
                    store?: string;
                    from?: string;
                    to?: string;
                    range?: "7d" | "30d" | "quarter";
                    limit?: number;
                    needsReview?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VisitSummary"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/visits/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * One visit, complete.
         * @description Utterances, speakers, segments, observations, scores and coaching in a single response. The monolith made eight separate database round trips for this, all against the same document.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["VisitDetail"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            detail?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/conversations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Conversation feed with transcripts, for the explorer. */
        get: {
            parameters: {
                query?: {
                    store?: string;
                    from?: string;
                    to?: string;
                    range?: "7d" | "30d" | "quarter";
                    limit?: number;
                    needsReview?: "true" | "false";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ConversationFeedItem"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coaching": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Coaching items across visits, highest priority first. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CoachingRow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/followups": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Open leads, overdue first. */
        get: {
            parameters: {
                query?: {
                    store?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["FollowUpRow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/overview": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Headline metrics, per-store rollup and the top behaviour misses. */
        get: {
            parameters: {
                query?: {
                    /** @description Store id, or "all"/omitted for every store. */
                    store?: string;
                    range?: "7d" | "30d" | "quarter";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Overview"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/home-trend": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Visits, store health, conversion and opportunity over time.
         * @description Daily buckets up to 35 days, Monday-start weekly beyond that.
         */
        get: {
            parameters: {
                query?: {
                    /** @description Store id, or "all"/omitted for every store. */
                    store?: string;
                    range?: "7d" | "30d" | "quarter";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["HomeTrend"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/observation-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Per-observation yes/no/unclear tallies and miss rate, by store.
         * @description `unclear` is excluded from the miss-rate denominator, never counted as a failure.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ObservationStat"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/sales": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The six sales-floor metrics with trends. */
        get: {
            parameters: {
                query?: {
                    /** @description Store id, or "all"/omitted for every store. */
                    store?: string;
                    range?: "7d" | "30d" | "quarter";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalesMetrics"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/sales/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Per-associate sales scorecard. */
        get: {
            parameters: {
                query?: {
                    store?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["SalesStaffRow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/analytics/product-demand": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Customer-raised product demand, joined to what we could not supply. */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ProductDemandRow"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/audio": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse a recording already uploaded to S3.
         * @description Send the object URI and the visit metadata. Big Ears presigns the object and hands that URL to the speech-to-text provider — the audio never passes through this service. Returns immediately; poll GET /v1/jobs/{id} for phase, log and result.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description s3://bucket/key, or a bare key resolved against S3_BUCKET. */
                        s3Uri: string;
                        storeId: string;
                        storeName?: string;
                        staffId: string;
                        staffName: string;
                        /** Format: email */
                        staffEmail?: string;
                        startedAt?: string;
                        /** @default hi-en */
                        language?: string;
                        transcriptId?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAccepted"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            detail?: string;
                        };
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            detail?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/ingest/transcript": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Analyse a transcript directly, with no audio.
         * @description The engine consumes transcripts, not audio — speech-to-text is one producer of a DiarizedTranscript and a hand-written one is another. This route is how you exercise the pipeline without a recording.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description A DiarizedTranscript. Validated against the engine schema on submit. */
                        transcript?: unknown;
                        staffId?: string;
                        staffName?: string;
                    };
                };
            };
            responses: {
                /** @description Default Response */
                202: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["JobAccepted"];
                    };
                };
                /** @description Default Response */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            detail?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Job status, phase and log tail.
         * @description Poll this every couple of seconds while an ingest runs. `log` is the rolling tail of pipeline events and is what the upload screen renders; unlike a stream it survives a page refresh.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"];
                    };
                };
                /** @description Default Response */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            detail?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Recent ingest jobs, newest first. */
        get: {
            parameters: {
                query?: {
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["Job"][];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/copilot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask a question about the store data. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        question: string;
                        history?: {
                            role: string;
                            content: string;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["CopilotAnswer"];
                    };
                };
                /** @description Default Response */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            error: string;
                            detail?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/export/visits.csv": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Visits as CSV. */
        get: {
            parameters: {
                query?: {
                    /** @description Store id, or "all"/omitted for every store. */
                    store?: string;
                    range?: "7d" | "30d" | "quarter";
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Default Response */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Store: {
            id: string;
            name: string;
        };
        Staff: {
            id: string;
            name: string;
            store_id: string;
            email: string | null;
            active: boolean;
        };
        StaffPerformance: {
            staff_id: string;
            staff_name: string;
            store_id: string;
            visits: number;
            overall_score: number | null;
            hospitality_score: number | null;
            sales_score: number | null;
            accuracy_score: number | null;
            conversion_pct: number | null;
        };
        VisitSummary: {
            id: string;
            store_id: string;
            store_name: string;
            staff_id: string | null;
            staff_name: string | null;
            started_at: string;
            duration_sec: number | null;
            outcome: string;
            outcome_value_inr: number | null;
            sale_made: boolean | null;
            overall_score: number | null;
            role_confidence: number | null;
            needs_review: boolean;
            headline: string | null;
            manager_summary: string | null;
            hospitality_score: number | null;
            sales_score: number | null;
            accuracy_score: number | null;
            intent_level: string | null;
            blocker: string | null;
            estimated_value_inr: number | null;
        };
        VisitDetail: {
            visit: components["schemas"]["VisitSummary"];
            customer_signal: {
                purchase_intent: string;
                intent_confidence: number | null;
                intent_reasoning: string;
                occasion: string;
                budget_band: string | null;
                urgency: string;
                primary_blocker: string;
                blocker_detail: string | null;
                emotional_state: string;
                recommended_action: string;
                estimated_value_inr: number | null;
            } | null;
            utterances: {
                idx: number;
                start_ms: number;
                end_ms: number | null;
                text: string;
                text_redacted: string | null;
                speaker_id: string | null;
            }[];
            excluded_utterances: {
                original_index: number;
                start_ms: number;
                text: string;
                speaker: string;
                excluded_by: string;
                issue_type: string | null;
                confidence: number;
                reasoning: string | null;
            }[];
            speakers: {
                id: string;
                diarization_label: string;
                role: string;
                confidence: number | null;
                reasoning: string | null;
            }[];
            segments: {
                phase: string;
                start_index: number;
                end_index: number;
                summary: string | null;
            }[];
            observations: {
                observation_id: string;
                agent_name: string;
                value: string;
                confidence: number | null;
                evidence_quote: string | null;
                utterance_index: number | null;
                reasoning: string | null;
                label: string;
                criterion: string | null;
                inverted: boolean;
            }[];
            scores: {
                dimension: string;
                value: number | null;
                earned_points: number | null;
                available_points: number | null;
                coverage: number | null;
            }[];
            coaching: components["schemas"]["CoachingRow"][];
        };
        CoachingRow: {
            id: string;
            visit_id: string;
            staff_id: string | null;
            category: string;
            priority: string;
            observation: string;
            suggested_alternative: string | null;
        };
        ConversationFeedItem: {
            id: string;
            started_at: string;
            time: string;
            store: string;
            associate: string;
            duration: string;
            duration_sec: number | null;
            needsReview: boolean;
            confidence: number | null;
            hospitality: number | null;
            accuracy: number | null;
            /** @enum {string|null} */
            objection: "yes" | "no" | "unclear" | null;
            /** @enum {string} */
            upsell: "Yes" | "No" | "—";
            intent: string | null;
            /** @enum {string} */
            outcome: "converted" | "not_converted" | "callback" | "unknown";
            summary: {
                objection: string;
                hospitality: string;
                upsell: string;
                intent: string;
            };
            transcript: {
                t: string;
                /** @enum {string} */
                who: "staff" | "customer";
                name: string;
                text: string;
            }[];
        };
        FollowUpRow: {
            visit_id: string;
            store: string;
            associate: string | null;
            reason: string | null;
            last_visit: string;
            scheduled: string | null;
            /** @enum {string} */
            status: "overdue" | "pending";
            intent_level: string;
            estimated_value_inr: number | null;
            contact_on_file: boolean;
        };
        ObservationStat: {
            observation_id: string;
            agent_name: string;
            store_id: string;
            label: string;
            inverted: boolean;
            yes_count: number;
            no_count: number;
            unclear_count: number;
            total: number;
            miss_rate_pct: number | null;
        };
        Overview: {
            visits: components["schemas"]["VisitSummary"][];
            staff: components["schemas"]["StaffPerformance"][];
            storePerf: {
                id: string;
                name: string;
                visits: number;
                overall: number | null;
                conversion: number | null;
            }[];
            totalVisits: number;
            overall: number | null;
            hospitality: number | null;
            sales: number | null;
            accuracy: number | null;
            conversion: number | null;
            needsReview: number;
            opportunity: number;
            topIssues: {
                id: string;
                label: string;
                missRate: number;
                count: number;
                inverted: boolean;
            }[];
        };
        HomeTrend: {
            labels: string[];
            visits: number[];
            storeHealth: (number | null)[];
            conversion: (number | null)[];
            opportunityRevenue: number[];
        };
        SalesMetrics: {
            labels: string[];
            series: {
                sales: {
                    current: number | null;
                    trend: (number | null)[];
                };
                hospitality: {
                    current: number | null;
                    trend: (number | null)[];
                };
                accuracy: {
                    current: number | null;
                    trend: (number | null)[];
                };
                objection: {
                    current: number | null;
                    trend: (number | null)[];
                };
                attach: {
                    current: number | null;
                    trend: (number | null)[];
                };
                offer: {
                    current: number | null;
                    trend: (number | null)[];
                };
            };
        };
        SalesStaffRow: {
            staff_id: string;
            staff_name: string;
            store_name: string;
            sales: number | null;
            hospitality: number | null;
            accuracy: number | null;
            objection: number | null;
            attach: number | null;
            offer: number | null;
            composite: number | null;
        };
        ProductDemandRow: {
            product: string;
            category: string;
            mentions: number;
            inStock: boolean;
            lostValueInr: number;
            lostVisits: number;
        };
        JobAccepted: {
            jobId: string;
            /** @enum {string} */
            status: "queued";
        };
        /** @enum {string} */
        JobPhase: "queued" | "download" | "stt" | "persist" | "reconcile" | "analysis" | "scoring" | "done";
        Job: {
            jobId: string;
            /** @enum {string} */
            kind: "audio" | "transcript";
            /** @enum {string} */
            status: "queued" | "running" | "succeeded" | "failed";
            phase: components["schemas"]["JobPhase"];
            storeId: string;
            staffId: string;
            s3Uri: string | null;
            createdAt: string;
            startedAt: string | null;
            finishedAt: string | null;
            result: {
                transcriptId: string;
                visits: {
                    visitId: string;
                    overallScore: number | null;
                    isNew: boolean;
                }[];
                reconciliationSummary: string;
            } | null;
            error: string | null;
            log: {
                at: string;
                message: string;
            }[];
        };
        CopilotAnswer: {
            answer: string;
            source: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
